name: school_banner
description: Package providing some utilities to interface with Ellucian's Banner api.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
